name: Build and Deploy

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Build
        run: |
          yarn install

          cd example-app && yarn install
          cd ../extra-dependencies && yarn install
          cd ..
          yarn run:gen-fs

          yarn build
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          folder: build

      - name: Upload-Artifact-For-Debug
        uses: actions/upload-artifact@v4
        with:
          name: my-build-result
          path: build
          include-hidden-files: true
